import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import { useRouter } from 'next/router';
import HomePage from 'components/Home/HomePage/HomePage';

export default function Home() {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>DoctoRx - doctor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <h1 onClick={() => router.push('/video_chat')}>Video</h1>
        <h1 onClick={() => router.push('/chat')}>Chat</h1>
        <h1 onClick={() => router.push('/voice_chat')}>Voice</h1> */}

        <HomePage />
      </main>
    </div>
  );
}
